from pathlib import Path
import chromadb
from chromadb.utils import embedding_functions

# ---------- Paths ----------
BASE_DIR = Path(__file__).resolve().parents[2]
CHROMA_DIR = BASE_DIR / "storage" / "chroma"
CHROMA_DIR.mkdir(parents=True, exist_ok=True)

# ---------- Embedding Function ----------
embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name="all-MiniLM-L6-v2"
)

# ---------- Chroma Client ----------
client = chromadb.PersistentClient(
    path=str(CHROMA_DIR)
)

# ---------- Collection ----------
collection = client.get_or_create_collection(
    name="multimedia_chunks",
    embedding_function=embedding_fn
)

# ---------- Store ----------
def store_chunks(chunks: list):
    """
    Store text chunks in Chroma.
    Embeddings are automatically generated by Chroma.
    """

    if not chunks:
        return

    ids = [f"{c['source']}_{c['chunk_id']}" for c in chunks]
    documents = [c["text"] for c in chunks]
    metadatas = [
        {
            "source": c["source"],
            "chunk_id": c["chunk_id"],
            "start_time": c.get("start_time"),
            "end_time": c.get("end_time"),
        }
        for c in chunks
    ]

    collection.add(
        ids=ids,
        documents=documents,
        metadatas=metadatas
    )

    print(f"Stored {len(chunks)} chunks in Chroma")

# ---------- Query ----------
def query_chunks(query: str, n_results: int = 5):
    """
    Semantic search over stored chunks.
    """

    return collection.query(
        query_texts=[query],
        n_results=n_results
    )


